[book]
authors = ["u2usvc"]
language = "en"
src = "src"
title = "CSNotes"

[output.html]
git-repository-url = "https://github.com/u2usvc/cs-notes"
# no-section-label = true
default-theme = "ayu"
preferred-dark-theme = "ayu"
mathjax-support = true
additional-css = ["custom.css"]

[output.html.fold]
enable = true
